actionified, formatted and doxy'd
adafruit/Adafruit_SGP30 pull request #13
Opened 2020-05-08 01:20 UTC by siddacious

2020-05-08 16:13 UTC, ladyada requested changes

2020-05-08 16:13 UTC, ladyada commented on library.properties
> +ruthor=Adafruit
fix

2020-05-08 17:57 UTC, siddacious commented on library.properties
> +ruthor=Adafruit
@ladyada fixed

2020-05-10 00:49 UTC, ladyada approved these changes

2020-05-10 00:50 UTC, merged